PSP_BEGIN_EXPORTS

PSP_EXPORT_START(syslib, 0, 0x8000)
PSP_EXPORT_FUNC_HASH(module_start)
PSP_EXPORT_VAR_HASH(module_info)
PSP_EXPORT_END

PSP_EXPORT_START(HookTest, 0, 0x4001)
PSP_EXPORT_FUNC(vshCtrlReadBufferPositiveFake)
PSP_EXPORT_FUNC(sceCtrlReadBufferPositiveFake)
PSP_EXPORT_FUNC(sceCtrlReadBufferNegativeFake)
PSP_EXPORT_FUNC(sceCtrlPeekBufferPositiveFake)
PSP_EXPORT_FUNC(sceCtrlPeekBufferNegativeFake)
PSP_EXPORT_END

PSP_END_EXPORTS 